version: "3"
services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server
    deploy:
      resources:
        limits:
          memory: 3072m
    ports:
      - 1401:1433
    tty: true
    stdin_open: true
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password-123
    container_name: msql
    volumes:
      - "data:/mydata/"
