version: "3"
services:
    server:
        deploy:
            resources:
                limits:
                    memory: 3072m
        tty: true
        stdin_open: true
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=password-123
        ports:
            - 1401:1433
        container_name: msql
        volumes:
            - "./data/:/mydata/"
        image: mcr.microsoft.com/mssql/server
