services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.1.0
    container_name: uptime-kuma
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ~/dc-data/kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
