version: "3.8"
services:
  proxy:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "~/dc-data/proxy/data:/data"
      - "~/dc-data/proxy/letsencrypt:/etc/letsencrypt"
