version: "3"
services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - "~/dc-data/mailpit/:/data"
    environment:
      - MP_DATABASE=/data/mailpit.db
      # - MP_UI_AUTH_FILE=/data/authfile # for password setup
      - TZ=Europe/London
    ports:
      - 8025:8025
      - 1025:1025
