version: "3"
services:
    cassandra:
        container_name: cas
        ports:
            - 9042:9042
        tty: true
        stdin_open: true
        deploy:
            resources:
                limits:
                    memory: 3500m
        image: cassandra:3
