version: "3"
services:
  cassandra:
    image: cassandra:3
    deploy:
      resources:
        limits:
          memory: 3500m
    ports:
      - 9042:9042
    tty: true
    stdin_open: true
    container_name: cas
    volumes:
      - "~/dc-data/cassandra:/var/lib/cassandra"
