services:
  actual-server:
    image: actualbudget/actual-server:25.4.0
    container_name: actual
    restart: unless-stopped
    ports:
      - 3004:5006
    volumes:
      - "~/dc-data/actual/:/data"
