version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "3008:8081"
    volumes:
      - "~/dc-data/metube/:/downloads"
