services:
  web:
    image: ghcr.io/karakeep-app/karakeep:0.31.0 # https://github.com/karakeep-app/karakeep/releases
    container_name: karakeep
    restart: unless-stopped
    volumes:
      - ~/dc-data/hoarder/data:/data
    ports:
      - 3013:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data

  meilisearch:
    mem_limit: 400m
    image: getmeili/meilisearch:v1.11.1
    container_name: karakeep-meili
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ~/dc-data/hoarder/meili_data:/meili_data
