version: "3.8"
services:
  web:
    image: ghcr.io/karakeep-app/karakeep:0.26.0 # https://github.com/karakeep-app/karakeep/releases
    restart: unless-stopped
    volumes:
      - ~/dc-data/hoarder/data:/data
    ports:
      - 3013:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      #BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data

  meilisearch:
    mem_limit: 400m
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ~/dc-data/hoarder/meili_data:/meili_data

  # chrome:
  #   image: gcr.io/zenika-hub/alpine-chrome:123
  #   restart: unless-stopped
  #   command:
  #     - --no-sandbox
  #     - --disable-gpu
  #     - --disable-dev-shm-usage
  #     - --remote-debugging-address=0.0.0.0
  #     - --remote-debugging-port=9222
  #     - --hide-scrollbars
