services:
  calibre-web:
    image: crocodilestick/calibre-web-automated:V3.1.4
    container_name: calibre-web
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - HARDCOVER_TOKEN=${HARDCOVER_TOKEN} # https://hardcover.app/account/api
    volumes:
      - ~/dc-data/calibre/config:/config
      - ~/dc-data/calibre/library:/calibre-library
      - ~/dc-data/calibre/ingest:/cwa-book-ingest

    ports:
      - "3016:8083"
    restart: unless-stopped

  shelfmark:
    image: ghcr.io/calibrain/shelfmark:1.1.2
    container_name: shelfmark
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - USING_TOR=true
      - FLASK_PORT=8084
      - CWA_INGEST_PATH=/cwa-book-ingest
      - CALIBRE_WEB_URL=https://books.b0xy.xyz
      - BOOK_LANGUAGE=en,de,uk,ru
    volumes:
      - ~/dc-data/shelfmark/config:/config
      - ~/dc-data/calibre/ingest:/cwa-book-ingest
      - ~/dc-storage/audiobookshelf/audiobooks:/audiobooks
    ports:
      - "3017:8084"
    restart: unless-stopped
