version: "3.8"
services:
  calibre-web:
    image: linuxserver/calibre-web:0.6.22
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 # optional
    volumes:
      - "~/dc-data/calibre/config:/config"
      - "~/dc-data/calibre/library:/books"
    ports:
      - 3010:8083
    restart: unless-stopped
