version: "3"

services:
  db:
    image: postgis/postgis:14-3.2-alpine
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - "~/dc-data/geo-postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=dockerx"
      - "POSTGRES_USER=dockerx"
      - "POSTGRES_PASSWORD=dockerx"
      - "PG_DATA=/data/postgres"
    ports:
      - 5432:5432

  dbgate:
    image: dbgate/dbgate
    restart: always
    volumes:
      - "~/dc-data/dbgate:/root/.dbgate"
    environment:
      CONNECTIONS: con1
      LABEL_con1: Postgres
      SERVER_con1: db
      USER_con1: dockerx
      PASSWORD_con1: dockerx
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
    ports:
      - 80:3000
