services:
  db:
    image: postgres:15.3
    container_name: postgres
    command: ["postgres", "-c", "log_statement=all"]
    restart: unless-stopped
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ~/dc-data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8085:80
    volumes:
      - ~/dc-data/pgadmin:/var/lib/pgadmin # Must sudo chmod 5050 ./local-data/
