# For all scrape jobs.
global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # For container monitoring
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # For overall system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
